-- Builds VerifiedData.lua from one or more Merchant Map SavedVariables files.
-- Existing entries in VerifiedData.lua are kept. Newer visits update position and prices; items from all visits are kept.
--
-- Usage (from the addon folder):
--   lua Tools/BuildVerifiedData.lua VerifiedData.lua "<WoW>/WTF/Account/<ACCOUNT>/SavedVariables/MerchantMap.lua" [more files...]

local outPath = arg[1]
if not (outPath and arg[2]) then
    print("Usage: lua BuildVerifiedData.lua <VerifiedData.lua> <SavedVariables file> [more files...]")
    os.exit(1)
end

local function Load(path, env)
    local chunk, err = loadfile(path, "t", env)
    if not chunk then return nil, err end
    if setfenv and env then setfenv(chunk, env) end
    return chunk
end

-- Current shipped data
local vendors, services, itemNames = {}, {}, {}
local current = Load(outPath)
if current then
    local MM = {}
    current(nil, MM)
    vendors, services, itemNames = MM.shippedVendors or {}, MM.shippedServices or {}, MM.shippedItemNames or {}
end

-- Merge each SavedVariables file
local added = { vendors = 0, services = 0 }
for i = 2, #arg do
    local env = {}
    local chunk = assert(Load(arg[i], env))
    chunk()
    local db = env.MerchantMapDB or env.VendorAtlasDB -- older files from before the rename
    assert(db, arg[i] .. " has no MerchantMapDB")

    for key, vendor in pairs(db.vendors or {}) do
        local old = vendors[key]
        if vendor.mapID and vendor.lastSeen and (not old or old[5] ~= vendor.lastSeen) then
            local stock = {}
            for itemID in pairs(vendor.items) do
                local item = db.items[itemID]
                local offer = item and item.vendors[key]
                if offer then
                    stock[itemID] = { offer.price, offer.cost, offer.limited, offer.pvp }
                    itemNames[itemID] = item.name or itemNames[itemID]
                end
            end
            -- The newer visit wins, but items only the other one saw (class, race, rank) are kept
            local newer = not old or old[5] < vendor.lastSeen
            for itemID, offer in pairs(old and old[6] or {}) do
                if not newer or not stock[itemID] then stock[itemID] = offer end
            end
            -- Classic items not seen in this shop: noted by either visit, unless one of them saw it
            local notSeen = {}
            for _, itemID in ipairs(old and old[8] or {}) do notSeen[itemID] = true end
            for itemID in pairs(vendor.notSeen or {}) do notSeen[itemID] = true end
            local list = {}
            for itemID in pairs(notSeen) do
                if not stock[itemID] then list[#list + 1] = itemID end
            end
            table.sort(list)
            if newer then
                vendors[key] = { vendor.name, vendor.mapID, vendor.x, vendor.y, vendor.lastSeen, stock, vendor.seedID, list }
            else
                old[6], old[8] = stock, list
            end
            added.vendors = added.vendors + 1
        end
    end

    for key, seen in pairs(db.verifiedServices or {}) do
        local old = services[key]
        if not old or old[5] < seen.t then
            -- New NPCs (not in the Classic data) also carry their paths and faction
            services[key] = {
                seen.name, seen.mapID, seen.x, seen.y, seen.t,
                seen.paths or (old and old[6]), seen.faction or (old and old[7]), seen.title or (old and old[8]),
            }
            added.services = added.services + 1
        end
    end
end

-- Writing ------------------------------------------------------------------

local function Value(v)
    if type(v) == "string" then return (("%q"):format(v):gsub("\\\n", "\\n")) end
    if type(v) == "number" and v % 1 ~= 0 then return ("%.4f"):format(v) end
    if type(v) == "table" then
        local parts = {}
        for i, s in ipairs(v) do parts[i] = Value(s) end
        return "{ " .. table.concat(parts, ", ") .. " }"
    end
    return tostring(v)
end

-- Numbers before strings, then ascending
local function SortedKeys(t)
    local keys = {}
    for k in pairs(t) do keys[#keys + 1] = k end
    table.sort(keys, function(a, b)
        if type(a) ~= type(b) then return type(a) == "number" end
        return a < b
    end)
    return keys
end

-- Positional list, keeping nils in the middle
local function List(t, n)
    local parts = {}
    for i = 1, n do parts[i] = Value(t[i]) end
    while parts[#parts] == "nil" do parts[#parts] = nil end
    return "{ " .. table.concat(parts, ", ") .. " }"
end

local out = {
    "-- Generated by Tools/BuildVerifiedData.lua from in-game verified data. Don't edit by hand.",
    "local _, MM = ...",
    "",
    "-- [key] = { name, mapID, x, y, lastSeen, { [itemID] = { price, cost, limited, pvp } }, seedID, { Classic items not seen in this shop } }",
    "MM.shippedVendors = {",
}
for _, key in ipairs(SortedKeys(vendors)) do
    local v = vendors[key]
    local stock = {}
    for _, itemID in ipairs(SortedKeys(v[6])) do
        stock[#stock + 1] = ("[%d] = %s"):format(itemID, List(v[6][itemID], 4))
    end
    out[#out + 1] = ("    [%s] = { %s, %s, %s, %s, %s, { %s }, %s, %s },"):format(
        Value(key), Value(v[1]), Value(v[2]), Value(v[3]), Value(v[4]), Value(v[5]), table.concat(stock, ", "), Value(v[7]),
        Value(v[8] or {}))
end
out[#out + 1] = "}"
out[#out + 1] = ""
out[#out + 1] = "-- [\"s\" .. npcID] = { name, mapID, x, y, verifiedAt, paths, faction, title } (last three only for NPCs new in Forever)"
out[#out + 1] = "MM.shippedServices = {"
for _, key in ipairs(SortedKeys(services)) do
    out[#out + 1] = ("    [%s] = %s,"):format(Value(key), List(services[key], 8))
end
out[#out + 1] = "}"
out[#out + 1] = ""
out[#out + 1] = "MM.shippedItemNames = {"
for _, itemID in ipairs(SortedKeys(itemNames)) do
    out[#out + 1] = ("    [%d] = %s,"):format(itemID, Value(itemNames[itemID]))
end
out[#out + 1] = "}"

local file = assert(io.open(outPath, "w"))
file:write(table.concat(out, "\n"), "\n")
file:close()

local function Count(t) local n = 0 for _ in pairs(t) do n = n + 1 end return n end
print(("Updated %d vendors and %d services. %s now has %d vendors and %d services."):format(
    added.vendors, added.services, outPath, Count(vendors), Count(services)))
